services:
  - type: web
    name: gitops-sample-webserver
    runtime: image
    image:
      url: docker.io/library/nginx:alpine
    plan: free
    envVars:
      - key: PORT
        value: "10000"
      - key: NGINX_PORT
        value: "10000"