previews:
  generation: automatic

services:
  - type: web
    name: gitops-sample-webserver
    runtime: static
    publishDir: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html